
    // This file is auto-generated by react-native-sbermarket-engine
    
    export default {
      'module-products': () => require('module-products').default,
  'module-settings': () => require('module-settings').default
    };
    