// This file was generated by react-native-sbermarket-enginee on Tue May 11 2021
// You can extend it if you want, but leave the defaults to be required from the engine config
module.exports = {
...require('./node_modules/react-native-sbermarket-engine/tools/engine_cli/etc/metro.config')
};
